# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExoscaleCli < Formula
  desc "Manage easily your Exoscale infrastructure from the command-line."
  homepage "https://community.exoscale.com/tools/command-line-interface/"
  version "1.95.6"

  on_macos do
    url "https://github.com/exoscale/cli/releases/download/v1.95.6/exoscale-cli_1.95.6_darwin_all.tar.gz"
    sha256 "6b7695ae36e534a6461cc4f799c982ff6db856835ad83863e735775b5ff1c889"

    def install
      bin.install "exo"
      man1.install Dir["manpage/exo*.1"]
      bash_completion.install "contrib/completion/bash/exo"
      fish_completion.install "contrib/completion/fish/exo"
      zsh_completion.install "contrib/completion/zsh/_exo"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/exoscale/cli/releases/download/v1.95.6/exoscale-cli_1.95.6_linux_amd64.tar.gz"
      sha256 "5808b1e034244e5458081c58d013e85255df74e6119dca21c4404275f87213a6"
      def install
        bin.install "exo"
        man1.install Dir["manpage/exo*.1"]
        bash_completion.install "contrib/completion/bash/exo"
        fish_completion.install "contrib/completion/fish/exo"
        zsh_completion.install "contrib/completion/zsh/_exo"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/exoscale/cli/releases/download/v1.95.6/exoscale-cli_1.95.6_linux_armv6.tar.gz"
      sha256 "960efef715cbcdca47de2c04f56a9d68db6b6ef269dcb0db785f279c6de3d9f9"
      def install
        bin.install "exo"
        man1.install Dir["manpage/exo*.1"]
        bash_completion.install "contrib/completion/bash/exo"
        fish_completion.install "contrib/completion/fish/exo"
        zsh_completion.install "contrib/completion/zsh/_exo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/exoscale/cli/releases/download/v1.95.6/exoscale-cli_1.95.6_linux_arm64.tar.gz"
      sha256 "ae947c8d03ab953084188fd27a37c5761234788bb38761de6ee70bb002012c76"
      def install
        bin.install "exo"
        man1.install Dir["manpage/exo*.1"]
        bash_completion.install "contrib/completion/bash/exo"
        fish_completion.install "contrib/completion/fish/exo"
        zsh_completion.install "contrib/completion/zsh/_exo"
      end
    end
  end
end
