# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExoscaleCli < Formula
  desc "Manage easily your Exoscale infrastructure from the command-line."
  homepage "https://exoscale.github.io/cli/"
  version "1.72.1"

  on_macos do
    url "https://github.com/exoscale/cli/releases/download/v1.72.1/exoscale-cli_1.72.1_darwin_all.tar.gz"
    sha256 "4055d94b6d3db713e948a3537c9418de27b985d728271c9a64242fe9d49025a9"

    def install
      bin.install "exo"
      man1.install Dir["manpage/exo*.1"]
      bash_completion.install "contrib/completion/bash/exo"
      zsh_completion.install "contrib/completion/zsh/_exo"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/exoscale/cli/releases/download/v1.72.1/exoscale-cli_1.72.1_linux_arm64.tar.gz"
      sha256 "46a083348864afa455358b247aacb4287381fbc1f85d31489bdf07d202904f17"

      def install
        bin.install "exo"
        man1.install Dir["manpage/exo*.1"]
        bash_completion.install "contrib/completion/bash/exo"
        zsh_completion.install "contrib/completion/zsh/_exo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/exoscale/cli/releases/download/v1.72.1/exoscale-cli_1.72.1_linux_armv6.tar.gz"
      sha256 "c0061a007ab6ab764fca1aba1decf81e620b6965580c8eb49b659b8885944590"

      def install
        bin.install "exo"
        man1.install Dir["manpage/exo*.1"]
        bash_completion.install "contrib/completion/bash/exo"
        zsh_completion.install "contrib/completion/zsh/_exo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/exoscale/cli/releases/download/v1.72.1/exoscale-cli_1.72.1_linux_amd64.tar.gz"
      sha256 "f80c1086d54d07619d9407aeb7e2644c0965aeef726a79de3068fb3efde76148"

      def install
        bin.install "exo"
        man1.install Dir["manpage/exo*.1"]
        bash_completion.install "contrib/completion/bash/exo"
        zsh_completion.install "contrib/completion/zsh/_exo"
      end
    end
  end
end
